In this notebook, we will go over how a genetic algorithm works. The only thing we need to write the code is numpy.

In [1]:
import numpy as np

A genetic algorithm works by mutating a population and selecting the best individuals from the population to make a new population. By doing this over and over again, we will have a population with better and better individuals. A population will consist of individuals and an individual will have a number of features. Putting all of these in a single numpy array will make performing computations on them easier. Below, we will create an array with ten individuals with three features each. Make sure the data type of your population is float, as it's important that the features can change by small amounts.

In [2]:
population = np.array([
    [10, 1, 22],
    [15, 3, 17],
    [12, 4, 36],
    [29, 2, 13],
    [25, 2, 24],
    [13, 1, 25],
    [12, 2, 14],
    [16, 5, 37],
    [27, 7, 18],
    [23, 3, 22],
], dtype=np.float)

Mutations are random changes. For this example, we will allow the features to increase or decrease by at most 20%. Increasing a value by 20% means multiplying it by 1.2 (1+20/100). Decreasing a value by 20% means multiplying it by 0.8 (1-20/100)

In [3]:
max_mutation_percentage = 20
max_mutation = 1 + (max_mutation_percentage / 100)
min_mutation = 1 - (max_mutation_percentage / 100)

print('max_mutation:', max_mutation)
print('min_mutation:', min_mutation)

max_mutation: 1.2
min_mutation: 0.8


Now let's create a randomly mutated population. First, we will have to make an array with random values with the same size as our population array. In case you didn't know: putting a * in front of a tuple when sending it as a parameter to a function sends the contents of the tuple to the function seperately instead.

In [4]:
mutation = np.random.rand(*population.shape)

print('mutation:', mutation)

mutation: [[0.79565259 0.41777199 0.9434719 ]
 [0.91655756 0.98786883 0.98102262]
 [0.7170526  0.14050483 0.83355297]
 [0.02251996 0.71714228 0.69615734]
 [0.49878394 0.45117432 0.46363709]
 [0.04760195 0.1356599  0.99854152]
 [0.49640043 0.54291049 0.01288477]
 [0.26665147 0.40715966 0.36905212]
 [0.44176959 0.50017638 0.64449605]
 [0.30140816 0.33812694 0.50056691]]


As you can see, the values range from 0 to 1. We want them to range from our min_mutation (0.8) to our max_mutation (1.2).

In [5]:
mutation = mutation * (max_mutation - min_mutation) + min_mutation

print('mutation:', mutation)

mutation: [[1.11826104 0.96710879 1.17738876]
 [1.16662302 1.19514753 1.19240905]
 [1.08682104 0.85620193 1.13342119]
 [0.80900798 1.08685691 1.07846294]
 [0.99951358 0.98046973 0.98545484]
 [0.81904078 0.85426396 1.19941661]
 [0.99856017 1.01716419 0.80515391]
 [0.90666059 0.96286387 0.94762085]
 [0.97670784 1.00007055 1.05779842]
 [0.92056326 0.93525078 1.00022676]]


All that's left is applying the mutation to the population.

In [6]:
mutated_population = mutation * population

print('population:', population)
print('mutated_population:', mutated_population)

population: [[10.  1. 22.]
 [15.  3. 17.]
 [12.  4. 36.]
 [29.  2. 13.]
 [25.  2. 24.]
 [13.  1. 25.]
 [12.  2. 14.]
 [16.  5. 37.]
 [27.  7. 18.]
 [23.  3. 22.]]
mutated_population: [[11.18261037  0.96710879 25.90255273]
 [17.49934536  3.5854426  20.27095379]
 [13.04185247  3.42480773 40.80316278]
 [23.46123149  2.17371382 14.02001818]
 [24.98783938  1.96093946 23.65091607]
 [10.64753013  0.85426396 29.98541518]
 [11.98272205  2.03432839 11.27215473]
 [14.5065694   4.81431933 35.06197136]
 [26.37111158  7.00049387 19.04037155]
 [21.17295508  2.80575233 22.00498879]]


That's great! This will already work and it's the most basic genetic algorithm possible. When you start getting close to the optimal values, you might not want to change all features anymore. Some features might already be optimal and changing them will just mess things up. We will only apply the mutation to **some** of the features to mitigate this. For this example, we will change 50% of all values. We will start with an array with random values with the same size as our population array, just like with the mutations. Then we make a boolean array to randomly select some of the mutations.

In [7]:
mutation_chance = 0.5 # 50%

chance = np.random.rand(*population.shape)

mask = chance < mutation_chance

print(mask)

[[False  True  True]
 [False False False]
 [ True False  True]
 [ True False  True]
 [ True  True False]
 [False  True False]
 [ True  True False]
 [ True False False]
 [ True  True False]
 [ True False  True]]


You can use boolean arrays to index arrays of the same size. Let's make a new population by copying the old one and applying the mutations.

In [8]:
new_population = np.copy(population)

new_population[mask] = mutated_population[mask]

print('population:', population)
print('new_population:', new_population)

population: [[10.  1. 22.]
 [15.  3. 17.]
 [12.  4. 36.]
 [29.  2. 13.]
 [25.  2. 24.]
 [13.  1. 25.]
 [12.  2. 14.]
 [16.  5. 37.]
 [27.  7. 18.]
 [23.  3. 22.]]
new_population: [[10.          0.96710879 25.90255273]
 [15.          3.         17.        ]
 [13.04185247  4.         40.80316278]
 [23.46123149  2.         14.02001818]
 [24.98783938  1.96093946 24.        ]
 [13.          0.85426396 25.        ]
 [11.98272205  2.03432839 14.        ]
 [14.5065694   5.         37.        ]
 [26.37111158  7.00049387 18.        ]
 [21.17295508  3.         22.00498879]]


As you can see, only some of the features were mutated. We will now make a function to mutate a population. In the function we don't make a new population. We instead change the population inplace.

In [9]:
def mutate(population, mutation_chance, max_mutation, min_mutation):
    # make an array with values from 0 to 1
    chance = np.random.rand(*population.shape)
    # create a mask array with the mutation chance
    mask = chance < mutation_chance
    
    # make an array with values from 0 to 1
    mutation = np.random.rand(*population.shape)
    # scale the array with min and max mutation
    mutation = mutation * (max_mutation - min_mutation) + min_mutation
    # make a fully mutated population
    mutated_population = mutation * population
    
    # partially apply the mutation to the population
    population[mask] = mutated_population[mask]

Genetic algorthms are usually used to either minimize a cost or maximize a score. In this case, we will minimize a cost. For this simple example we will make the features fit to the equation feature1 / feature2 = feature3. The cost will be the absolute difference between feature1 divided by feature2 and feature3. In reality you could calculate a cost or score based on how well an individual did in a game or simulation.

In [10]:
def calculate_cost(population):
    return np.abs((population[:, 0] / population[:, 1]) - population[:, 2])

cost = calculate_cost(population)

print(cost)

[12.         12.         33.          1.5        11.5        12.
  8.         33.8        14.14285714 14.33333333]


We now have 10 cost values. One for each individual. We now have to select some of the best ones. We will select 3 for now. To select the best we need to sort them on the cost first. In case you didn't know: argsort returns an array with the positions of the sorted elements of an array.

In [11]:
print(cost.argsort())

[3 6 4 0 1 5 8 9 2 7]


You can use an array of integers to index an array and create a new array.

In [12]:
print('old:', population)
print('new:', population[cost.argsort()])

old: [[10.  1. 22.]
 [15.  3. 17.]
 [12.  4. 36.]
 [29.  2. 13.]
 [25.  2. 24.]
 [13.  1. 25.]
 [12.  2. 14.]
 [16.  5. 37.]
 [27.  7. 18.]
 [23.  3. 22.]]
new: [[29.  2. 13.]
 [12.  2. 14.]
 [25.  2. 24.]
 [10.  1. 22.]
 [15.  3. 17.]
 [13.  1. 25.]
 [27.  7. 18.]
 [23.  3. 22.]
 [12.  4. 36.]
 [16.  5. 37.]]


Now lets get the best ones! Remember to sort the score from large to small .

In [13]:
n_to_select = 3

population = population[cost.argsort()]
best_selected = population[:n_to_select]

print(best_selected)

[[29.  2. 13.]
 [12.  2. 14.]
 [25.  2. 24.]]


Now it's time to make the new generation. While we can just select the best ones and mutate them a bit, we can also combine the best ones to make new ones. This mimicks nature where two plants or animals will make new plants or animals together. In this simple example this won't help at all. However, for more complex situations like video games and simulations it can help. If one individual makes **one** breakthrough and another individual makes a **different** one, their child will have **both** breakthroughs. We first randomly select the parents.

In [14]:
population_size, n_features = population.shape
n_parents = best_selected.shape[0]

parent1 = best_selected[np.random.randint(n_parents)]
parent2 = best_selected[np.random.randint(n_parents)]

print(parent1)
print(parent2)

[12.  2. 14.]
[25.  2. 24.]


We then make a child by randomly taking features from one parent or the other.

In [15]:
child = np.copy(parent1)
mask = np.random.rand(n_features) > 0.5
child[mask] = parent2[mask]

print(mask)
print(child)

[False  True False]
[12.  2. 14.]


Now let's combine some of these pieces of code to make a whole new generation.

In [16]:
n_to_select = 3

def make_new_generation(n_to_select, population, cost):
    # sort population by cost (low to high)
    population = population[cost.argsort()]
    # select the best
    best_selected = population[:n_to_select]
    # get some required values
    population_size, n_features = population.shape
    n_parents = best_selected.shape[0]
    # make new generation
    new_population = np.zeros_like(population)
    # fill the new generation
    for i in range(population_size):
        # select parents
        parent1 = best_selected[np.random.randint(n_parents)]
        parent2 = best_selected[np.random.randint(n_parents)]
        # combine to make child
        child = np.copy(parent1)
        mask = np.random.rand(n_features) > 0.5
        child[mask] = parent2[mask]
        # assign child to new population
        new_population[i] = child
    return new_population

new_population = make_new_generation(n_to_select, population, cost)

print(new_population)

[[27.  7. 17.]
 [10.  3. 17.]
 [10.  1. 22.]
 [15.  3. 18.]
 [15.  1. 17.]
 [10.  1. 22.]
 [15.  3. 17.]
 [27.  7. 17.]
 [27.  1. 22.]
 [15.  3. 17.]]


Now we will initialize some variables for the actual training. We define minimum and maximum values and then generate our starting population randomly. Then we train it and select the best.

In [17]:
population_size = 100  # 100 individuals per population
amount_of_features = 3
amount_of_generations = 20
amount_of_best_to_select = 10

max_mutation_percentage = 20
max_mutation = 1 + (max_mutation_percentage / 100)
min_mutation = 1 - (max_mutation_percentage / 100)
mutation_chance = 0.5  # 50%

# set minimum and maximum values
minimum_values = np.zeros([population_size, amount_of_features])  # leave as zeros
maximum_values = np.zeros([population_size, amount_of_features])
maximum_values[:, 0] = 1000  # feature1 has to be between 0 and 1000
maximum_values[:, 1] = 100  # feature2 has to be between 0 and 100
maximum_values[:, 2] = 100  # feature3 has to be between 0 and 100

# generate population with random values between minimum and maximum values
population = np.random.rand(population_size, amount_of_features)
population = population * (maximum_values - minimum_values) + minimum_values

# now we train it
for i in range(amount_of_generations):
    cost = calculate_cost(population)
    population = make_new_generation(amount_of_best_to_select, population, cost)
    mutate(population, mutation_chance, max_mutation, min_mutation)
    
    print('generation:', i, 'average cost:', np.mean(cost))

# finally, we extract the best result
cost = calculate_cost(population)
print('final average cost:', np.mean(cost))
print('final lowest cost:', np.min(cost))

population = population[cost.argsort()]
best_one = population[0]
print('best individual', best_one)
print('feature1/feature2:', best_one[0] / best_one[1], 'feature3:', best_one[2])
    

generation: 0 average cost: 60.68371842904447
generation: 1 average cost: 14.330409641193146
generation: 2 average cost: 7.4030757047147855
generation: 3 average cost: 3.8884995839388075
generation: 4 average cost: 3.557438947217258
generation: 5 average cost: 3.055642580790432
generation: 6 average cost: 1.3854338385452032
generation: 7 average cost: 1.3972543370211234
generation: 8 average cost: 1.4552693759507995
generation: 9 average cost: 1.4399647488409757
generation: 10 average cost: 1.706871356003285
generation: 11 average cost: 1.4963097149290865
generation: 12 average cost: 1.6630323265595406
generation: 13 average cost: 1.895037916602754
generation: 14 average cost: 1.8552702461909454
generation: 15 average cost: 1.64725854370629
generation: 16 average cost: 1.5076010339426715
generation: 17 average cost: 1.5962330878597604
generation: 18 average cost: 1.920436576908068
generation: 19 average cost: 1.6582054400198925
final average cost: 1.9635996472117434
final lowest cost: 

The difference between feature1/feature2 and feature3 should be pretty small now. This was a very simple problem, but the same method can be applied to actual simulations and video games.